name: Discrepancy in Trello REST API Documentation
description: Report a discrepancy in the Trello REST API documentation
title: ""
labels: ["documentation", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this discrepancy report!
  - type: textarea
    id: discrepancy-details
    attributes:
      label: What is the discrepancy?
      description: Please describe the discrepancy in detail.
      placeholder: Describe the discrepancy
      value: ""
    validations:
      required: true
  - type: dropdown
  id: api-version
  attributes:
    label: API Version
    description: Please select the version of the API documentation.
    options:
      - '1'
      - '2'
      - '3'
    default: 0
  validations:
    required: true
  - type: dropdown
    id: documentation-version
    attributes:
      label: Which version of the documentation are you using?
      options:
        - New View
      default: 1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        1. 
        1. 
        1. 
    validations:
      required: false  
  - type: dropdown
  id: documentation-version
  attributes:
    label: Which version of the documentation are you using?
    options:
      - Classic View
    default: 1
  validations:
    required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        1. 
        1. 
        1. 
    validations:
      required: false  
  - type: textarea
  id: impact
  attributes:
    label: What is the impact of this discrepancy?
    description: Please describe how this discrepancy affects your use of the API.
    placeholder: Describe the impact
  validations:
    required: false
  - type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Documentation**: Trello REST API documentation (both Classic View and New View)
        - **Browser**: Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)
        - **Operating System**: macOS Monterey Version 12.0.1
    value: |
        - Documentation: 
        - Browser:
        - Operating System:
    render: markdown
  validations:
    required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
